EmailSenderAspNetMvc/Controllers/AddressController.cs
using EmailSenderAspNetMvc.Models.Domains;
using EmailSenderAspNetMvc.Models.Repositories;
using EmailSenderAspNetMvc.Models.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmailSenderAspNetMvc.Controllers
{
    public class AddressController : Controller
    {
        EmailAddressRepository _emailAddressRepository = new EmailAddressRepository();

        public ActionResult EmailAddress(int id = 0)
        {
            var userId = User.Identity.GetUserId();

            var emailAddress = id == 0 ? GetNewDefinedEmailAddress(userId) :
                                          _emailAddressRepository.GetEmailAddress(id, userId);

            var vm = PrepareEditEmailAdressViewModel(emailAddress);

            return View(vm);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EmailAddress(EmailAddress emailAddress)
        {
            var userId = User.Identity.GetUserId();
            emailAddress.UserId = userId;
            emailAddress.IsDefined = true;

            if (!ModelState.IsValid)
            {
                var vm = PrepareEditEmailAdressViewModel(emailAddress);
                return View("Configuration", vm);
            }

            if (emailAddress.Id == 0)
            {
                _emailAddressRepository.AddEmailAddress(emailAddress);
            }
            else
            {
                _emailAddressRepository.UpdateDefinedEmailAddress(emailAddress);

            };
            return RedirectToAction("EmailAddresses");
        }
        private EmailAddress GetNewDefinedEmailAddress(string userId)
        {
            return new EmailAddress
            {
                UserId = userId,
                IsDefined = true
            };
        }

        private EditEmailAddressViewModel PrepareEditEmailAdressViewModel(EmailAddress emailAddress)
        {

            var vm = new EditEmailAddressViewModel
            {
                EmailAddress = emailAddress,
                Heading = emailAddress.Id != 0 ? "Edycja adresu" : "Dodawanie adresu"
            };
            return vm;
        }



        public ActionResult EmailAddresses()
        {

            var userId = User.Identity.GetUserId();

            List<EmailAddress> emailAddresses = _emailAddressRepository.GetDefinedEmailAddresses(userId);

            return View(emailAddresses);
        }



        [HttpPost]
        public ActionResult DeleteEmailAddress(int id)
        {
            try
            {
                var userId = User.Identity.GetUserId();
                _emailAddressRepository.DeleteDefinedEmailAddress(id, userId);

            }
            catch (Exception ex)
            {
                return Json(new { Success = false, Message = ex.Message });
            }


            return Json(new { Success = true });
        }
    }
}

EmailSenderAspNetMvc/Controllers/MailboxController.cs
using EmailSenderAspNetMvc.Models.Domains;
using EmailSenderAspNetMvc.Models.Repositories;
using EmailSenderAspNetMvc.Models.ViewModels;
using MailKit;
using MailKit.Net.Imap;
using MailKit.Search;
using MailKit.Security;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using MimeKit;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace EmailSenderAspNetMvc.Controllers
{
    [Authorize]
    public class MailboxController : Controller
    {
        EmailConfigurationRepository _emailConfigurationRepository = new EmailConfigurationRepository();
        EmailFolderRepository _emailFolderRepository = new EmailFolderRepository();
        EmailMessageFolderPairRepository _emailFolderMessagePairRepository = new EmailMessageFolderPairRepository();
        EmailMessageRepository _emailMessageRepository = new EmailMessageRepository();
        EmailAddressRepository _emailAddressRepository = new EmailAddressRepository();
        EmailAttachmentRepository _emailAttachmentRepository = new EmailAttachmentRepository();

        public ActionResult Folders(string message = null)
        {
            if (Session["EmailConfigurationId"] == null || (int)Session["EmailConfigurationId"] <= 0)
                return RedirectToAction("SelectConfiguration", "Configuration");

            var userId = User.Identity.GetUserId();


            var emailConfigurationId = (int)Session["EmailConfigurationId"];

            var emailConfiguration = _emailConfigurationRepository.GetEmailConfiguration(emailConfigurationId, userId);

            Synchronize(emailConfiguration, userId);

            var model = _emailFolderRepository.GetFolders(emailConfiguration);

            ViewBag.Message = message;

            return View(model);
        }

        private void Synchronize(EmailConfiguration emailConfiguration, string userId)
        {


            using (var imapClient = PrepareImapClient(emailConfiguration))
            {
                var imapFolders = SynchronizeFolders(imapClient,
                                                     emailConfiguration.Id,
                                                     userId);

                var imapFolderMessageUidsPairs = GetImapFolderUidsPairs(imapFolders);

                DetachOldMessagesFromFolders(imapFolderMessageUidsPairs,
                                             emailConfiguration.Id,
                                             userId);

                var newImapFolderUidsPairs = GetNewFolderUidsPairs(imapFolderMessageUidsPairs,
                                                                   emailConfiguration.Id,
                                                                   userId);



                var newImapFolderMessagesPairs = SynchronizeMessages(newImapFolderUidsPairs,
                                                                     emailConfiguration.Id,
                                                                     userId);

                SynchronizeNewMesageFolderPairs(newImapFolderMessagesPairs,
                                                emailConfiguration.Id,
                                                userId);

                imapClient.Disconnect(true);

                _emailMessageRepository.DeleteMessagesWithNoFolder(userId);

                _emailAddressRepository.DeleteAllNotReferencedEmailAddresses(userId);
            }

        }

        private IDictionary<IMailFolder, IList<UniqueId>> GetNewFolderUidsPairs(IDictionary<IMailFolder, IList<UniqueId>> imapFolderMessageUidsPairs,
                                                                                   int emailConfigurationId,
                                                                                   string userId)
        {
            var newFolderUidsPairs = new Dictionary<IMailFolder, IList<UniqueId>>();

            foreach (var item in imapFolderMessageUidsPairs)
            {
                var imapFolder = item.Key;
                var uids = item.Value;

                var newUids = _emailFolderMessagePairRepository.GetNewFolderMessageUids(imapFolder.FullName,
                                                                                        uids.Select(x => (long)x.Id).ToList(),
                                                                                        emailConfigurationId,
                                                                                        userId)
                                                               .Select(x => new UniqueId((uint)x))
                                                               .ToList();
                newFolderUidsPairs.Add(imapFolder, newUids);
            }

            return newFolderUidsPairs;


        }

        private void DetachOldMessagesFromFolders(IDictionary<IMailFolder, IList<UniqueId>> imapFolderMessageUidsPairs,
                                                  int emailConfigurationId,
                                                  string userId)
        {
            var newFolderMessagePairsDictionary = imapFolderMessageUidsPairs.ToDictionary(x => x.Key.FullName,
                                                                                          x => (IList<long>)x.Value
                                                                                                             .Select(y => (long)y.Id)
                                                                                                             .ToList());

            _emailFolderMessagePairRepository.DeleteOldFolderMessagePairs(newFolderMessagePairsDictionary,
                                                                          emailConfigurationId,
                                                                          userId);
        }

        private IDictionary<IMailFolder, IList<UniqueId>> GetImapFolderUidsPairs(IList<IMailFolder> imapFolders)
        {
            var imapFolderMessagesDictionary = new Dictionary<IMailFolder, IList<UniqueId>>();

            foreach (var imapFolder in imapFolders)
            {
                if (!imapFolder.Exists)
                    continue;

                imapFolder.Open(FolderAccess.ReadOnly);

                var imapUids = imapFolder.Search(SearchQuery.All)
                                         .ToList();



                imapFolderMessagesDictionary.Add(imapFolder, imapUids);

                imapFolder.Close();


            }

            return imapFolderMessagesDictionary;
        }

        private void SynchronizeNewMesageFolderPairs(IDictionary<IMailFolder, IList<(UniqueId, IMessageSummary)>> newImapFolderMessagesPairs,
                                                     int emailConfigurationId,
                                                     string userId)
        {

            var newEmailMessageFolderPairs = PrepareFolderMassagePairs(newImapFolderMessagesPairs,
                                                                       emailConfigurationId,
                                                                       userId);

            _emailFolderMessagePairRepository.AddFolderMessagePairs(newEmailMessageFolderPairs);

        }

        private IList<EmailMessageFolderPair> PrepareFolderMassagePairs(IDictionary<IMailFolder, IList<(UniqueId, IMessageSummary)>> imapFolderMessagesPairs,
                                                                        int emailConfigurationId,
                                                                        string userId)
        {
            var emailMessageFolderPairs = new List<EmailMessageFolderPair>();

            foreach (var imapFolderMessagesPair in imapFolderMessagesPairs)
            {
                var folderFullName = imapFolderMessagesPair.Key.FullName;
                var folderId = _emailFolderRepository.GetFolderId(folderFullName,
                                                                  emailConfigurationId,
                                                                  userId);

                foreach (var item in imapFolderMessagesPair.Value)
                {
                    var imapFolderMessageUid = (long)item.Item1.Id;
                    var imapMessageId = item.Item2.Envelope.MessageId;

                    var messageId = _emailMessageRepository.GetMessageId(imapMessageId,
                                                                               emailConfigurationId,
                                                                               userId);

                    emailMessageFolderPairs.Add(new EmailMessageFolderPair
                    {
                        UserId = userId,
                        EmailMessageId = messageId,
                        ImapMessageUid = imapFolderMessageUid,
                        EmailFolderId = folderId
                    });
                }
            }

            return emailMessageFolderPairs;
        }

        private IDictionary<IMailFolder, IList<(UniqueId, IMessageSummary)>> SynchronizeMessages(IDictionary<IMailFolder, IList<UniqueId>> imapFolderMessageUidsPairs,
                                                                                                 int emailConfigurationId,
                                                                                                 string userId)
        {

            var imapFolderMessagesDictionary = new Dictionary<IMailFolder, IList<(UniqueId, IMessageSummary)>>();

            foreach (var pair in imapFolderMessageUidsPairs)
            {
                var imapFolder = pair.Key;

                if (!imapFolder.Exists)
                    continue;

                var imapUids = pair.Value;

                imapFolder.Open(FolderAccess.ReadOnly);



                var imapMessageSummaries = imapFolder.Fetch(imapUids, MessageSummaryItems.UniqueId |

EmailSenderAspNetMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-expand-lg navbar-dark text-bg-primary mb-5">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">Strona główna</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link active dropdown-toggle" 
                           href="#" 
                           role="button" 
                           data-bs-toggle="dropdown">
                            Email
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                @Html.ActionLink("Ustawienia kont", "Configurations", "Configuration", null, new { @class = "dropdown-item" })
                            </li>
                            <li>
                                @Html.ActionLink("Książka adresowa", "EmailAddresses", "Address", null, new { @class = "dropdown-item" })
                            </li>
                            <li>
                                @Html.ActionLink("Utwórz wiadomość", "CreateMessage", "Message", null, new { @class = "dropdown-item" })
                            </li>
                            <li>
                                @Html.ActionLink("Skrzynka pocztowa", "Folders", "Mailbox", null, new { @class = "dropdown-item" })
                            </li>
                        </ul>
                    </li>          
                    <li class="nav-item">
                        @Html.ActionLink("O mnie", "About", "Home", null, new { @class = "nav-link active" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Kontakt", "Contact", "Home", null, new { @class = "nav-link active" })
                    </li>

                </ul>
            </div>
            @Html.Partial("_LoginPartial")
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Poczta internetowa</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")

    <div class="privacyPoliceInfo" style="display: none;">
        Serwis wykorzystuje pliki cookies. Korzystając ze strony wyrażasz zgodę na wykorzystanie plików cookies.
        <button onclick="closePrivacyPolice()" type="button" class="btn btn-light privacyPoliceBtn">Ok, rozumiem</button>
    </div>

    <script>
        function closePrivacyPolice() {
            $('.privacyPoliceInfo').css("display", "none");
            $.cookie("privacyPolicy", "1", { path: '/', expires: 365 });
        }

        $(document).ready(function () {
            if ($.cookie("privacyPolicy") !== "1")
                $('.privacyPoliceInfo').css("display", "");
           
        });
    </script>

    @RenderSection("scripts", required: false)

</body>
</html>