EmailSenderAspNetMvc/Controllers/FolderController.cs
using EmailSenderAspNetMvc.Models.Domains;
using EmailSenderAspNetMvc.Models.Repositories;
using EmailSenderAspNetMvc.Models.ViewModels;
using MailKit;
using MailKit.Net.Imap;
using MailKit.Search;
using MailKit.Security;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using MimeKit;
using Newtonsoft.Json;
using Org.BouncyCastle.Asn1.Cms;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http.Headers;
using System.Net.Mail;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.Services.Description;
using System.Web.UI.WebControls.WebParts;

namespace EmailSenderAspNetMvc.Controllers
{
    [Authorize]
    public class FolderController : Controller
    {
        EmailConfigurationRepository _emailConfigurationRepository = new EmailConfigurationRepository();
        EmailFolderRepository _emailFolderRepository = new EmailFolderRepository();
        EmailMessageFolderPairRepository _emailFolderMessagePairRepository = new EmailMessageFolderPairRepository();
        EmailFolderMessageRepository _emailFolderMessageRepository = new EmailFolderMessageRepository();
        EmailAddressRepository _emailAddressRepository = new EmailAddressRepository();
        EmailFolderAttachmentRepository _emailFolderAttachmentRepository = new EmailFolderAttachmentRepository();

        public ActionResult Folders()
        {

            var userId = User.Identity.GetUserId();
            Synchronize(_emailConfigurationRepository.GetEmailConfigurations(userId)[0], userId);

            var model = _emailFolderRepository.GetFolders(_emailConfigurationRepository.GetEmailConfigurations(userId)[0]);

            return View(model);
        }

        private void Synchronize(EmailConfiguration emailConfiguration, string userId)
        {


            var imapClient = PrepareImapClient(emailConfiguration);
            var imapFolders = SynchronizeFolders(imapClient,
                                                 emailConfiguration.Id,
                                                 userId);

            var imapFolderMessageUidsPairs = GetImapFolderUidsPairs(imapFolders);

            DetachOldMessagesFromFolders(imapFolderMessageUidsPairs,
                                         emailConfiguration.Id,
                                         userId);

            var newImapFolderUidsPairs = GetNewFolderUidsPairs(imapFolderMessageUidsPairs,
                                                               emailConfiguration.Id,
                                                               userId);



            var newImapFolderMessagesPairs = SynchronizeMessages(newImapFolderUidsPairs,
                                                                 emailConfiguration.Id,
                                                                 userId);

            SynchronizeNewMesageFolderPairs(newImapFolderMessagesPairs,
                                         emailConfiguration.Id,
                                         userId);

            imapClient.Disconnect(true);

            _emailFolderMessageRepository.DeleteFolderMessagesWithNoFolder(userId);

            _emailAddressRepository.DeleteAllNotReferencedEmailAddresses(userId);

        }

        private IDictionary<IMailFolder, IList<UniqueId>> GetNewFolderUidsPairs(IDictionary<IMailFolder, IList<UniqueId>> imapFolderMessageUidsPairs,
                                                                                   int emailConfigurationId,
                                                                                   string userId)
        {
            var newFolderUidsPairs = new Dictionary<IMailFolder, IList<UniqueId>>();

            foreach (var item in imapFolderMessageUidsPairs)
            {
                var imapFolder = item.Key;
                var uids = item.Value;

                var newUids = _emailFolderMessagePairRepository.GetNewFolderMessageUids(imapFolder.FullName,
                                                                                        uids.Select(x => (long)x.Id).ToList(),
                                                                                        emailConfigurationId,
                                                                                        userId)
                                                               .Select(x => new UniqueId((uint)x))
                                                               .ToList();
                newFolderUidsPairs.Add(imapFolder, newUids);
            }

            return newFolderUidsPairs;


        }

        private void DetachOldMessagesFromFolders(IDictionary<IMailFolder, IList<UniqueId>> imapFolderMessageUidsPairs,
                                                  int emailConfigurationId,
                                                  string userId)
        {
            var newFolderMessagePairsDictionary = imapFolderMessageUidsPairs.ToDictionary(x => x.Key.FullName,
                                                                                          x => (IList<long>)x.Value
                                                                                                             .Select(y => (long)y.Id)
                                                                                                             .ToList());

            _emailFolderMessagePairRepository.DeleteOldFolderMessagePairs(newFolderMessagePairsDictionary,
                                                                          emailConfigurationId,
                                                                          userId);
        }

        private IDictionary<IMailFolder, IList<UniqueId>> GetImapFolderUidsPairs(IList<IMailFolder> imapFolders)
        {
            var imapFolderMessagesDictionary = new Dictionary<IMailFolder, IList<UniqueId>>();

            foreach (var imapFolder in imapFolders)
            {
                if (!imapFolder.Exists)
                    continue;

                imapFolder.Open(FolderAccess.ReadOnly);

                var imapUids = imapFolder.Search(SearchQuery.All)
                                         .ToList();



                imapFolderMessagesDictionary.Add(imapFolder, imapUids);

                imapFolder.Close();


            }

            return imapFolderMessagesDictionary;
        }

        private void SynchronizeNewMesageFolderPairs(IDictionary<IMailFolder, IList<(UniqueId, IMessageSummary)>> newImapFolderMessagesPairs,
                                                     int emailConfigurationId,
                                                     string userId)
        {

            var newEmailMessageFolderPairs = PrepareFolderMassagePairs(newImapFolderMessagesPairs,
                                                                       emailConfigurationId,
                                                                       userId);

            _emailFolderMessagePairRepository.AddFolderMessagePairs(newEmailMessageFolderPairs);

        }

        private IList<EmailMessageFolderPair> PrepareFolderMassagePairs(IDictionary<IMailFolder, IList<(UniqueId, IMessageSummary)>> imapFolderMessagesPairs,
                                                                        int emailConfigurationId,
                                                                        string userId)
        {
            var emailMessageFolderPairs = new List<EmailMessageFolderPair>();

            foreach (var imapFolderMessagesPair in imapFolderMessagesPairs)
            {
                var folderFullName = imapFolderMessagesPair.Key.FullName;
                var folderId = _emailFolderRepository.GetFolderId(folderFullName,
                                                                  emailConfigurationId,
                                                                  userId);

                foreach (var item in imapFolderMessagesPair.Value)
                {
                    var imapFolderMessageUid = (long)item.Item1.Id;
                    var imapMessageId = item.Item2.Envelope.MessageId;

                    var messageId = _emailFolderMessageRepository.GetMessageId(imapMessageId,
                                                                               emailConfigurationId,
                                                                               userId);

                    emailMessageFolderPairs.Add(new EmailMessageFolderPair
                    {
                        UserId = userId,
                        EmailFolderMessageId = messageId,
                        ImapFolderMessageUid = imapFolderMessageUid,
                        EmailFolderId = folderId
                    });
                }
            }

            return emailMessageFolderPairs;
        }

        private IDictionary<IMailFolder, IList<(UniqueId, IMessageSummary)>> SynchronizeMessages(IDictionary<IMailFolder, IList<UniqueId>> imapFolderMessageUidsPairs,
                                                                                     int emailConfigurationId,
                                                                                     string userId)
        {

            var imapFolderMessagesDictionary = new Dictionary<IMailFolder, IList<(UniqueId, IMessageSummary)>>();

            foreach (var pair in imapFolderMessageUidsPairs)
            {
                var imapFolder = pair.Key;

                if (!imapFolder.Exists)
                    continue;

                var imapUids = pair.Value;

                imapFolder.Open(FolderAccess.ReadOnly);



                var imapMessageSummaries = imapFolder.Fetch(imapUids, MessageSummaryItems.UniqueId |
                                                                      MessageSummaryItems.Envelope |

EmailSenderAspNetMvc/Views/Folder/FolderMessage.cshtml
@using EmailSenderAspNetMvc.Models.ViewModels
@using EmailSenderAspNetMvc.Models.Domains
@using MailKit

@model DisplayEmailFolderMessageViewModel


<h3>

    @FolderIcon(@Model.EmailFolder.Attributes)
    @Model.EmailFolder.Name
</h3>

<div class="row">
    <div class="col-10">
        <button class="btn btn-sm btn-light"
                onclick="showFolderContent(@Model.EmailFolder.Id)">
            <i class="bi bi-arrow-left"></i>
        </button>
    </div>
    <div class="col-2 text-end">
        @(Model.EmailFolderMessage.Date.ToLocalTime().ToString("dd-MM-yyyy HH:mm"))
    </div>
</div>

<hr />

<div class="row">
    <h5 class="mb-3">
        @Model.EmailFolderMessage.Subject
    </h5>
</div>




<div class="row">
    <div class="col-12">

        @if (!string.IsNullOrEmpty(Model.EmailFolderMessage.From.DisplayName))
        {

            <table>
                <tr>
                    <td class="fw-bold pe-2">Od:</td>
                    <td>
                        <span class="fw-bold">
                            @Model.EmailFolderMessage.From.DisplayName
                        </span>
                        <span>
                            &lt;@Model.EmailFolderMessage.From.Address&gt;
                        </span>
                    </td>
                </tr>
            </table>



        }
        else
        {
            <h3>
                Od: @Model.EmailFolderMessage.From.Address
            </h3>
        }
        <div>
            @{
                var receiversTo = Model.EmailFolderMessage
                                             .EmailFolderMessageReceivers
                                             .Where(x => x.EmailMessageReceiverType == EmailMessageReceiverType.To)
                                             .ToList();
                if (receiversTo.Any())
                {
                    <table>

                        @for (int i = 0; i < receiversTo.Count; i++)
                        {
                            <tr>
                                <td class="pe-2">
                                    @if (i == 0)
                                    {
                                        <text>Do:</text>
                                    }
                                </td>
                                <td>
                                    @receiversTo[i].EmailAddress.AddressInfo
                                </td>
                            </tr>



                        }
                    </table>

                }

            }
        </div>
        <div>
            @{
                var receiversCc = Model.EmailFolderMessage
                                             .EmailFolderMessageReceivers
                                             .Where(x => x.EmailMessageReceiverType == EmailMessageReceiverType.CC)
                                             .ToList();
                if (receiversTo.Any())
                {
                    <table>

                        @for (int i = 0; i < receiversCc.Count; i++)
                        {
                            <tr>
                                <td class="pe-2">
                                    @if (i == 0)
                                    {
                                        <text>DW:</text>
                                    }
                                </td>
                                <td>
                                    @receiversCc[i].EmailAddress.AddressInfo
                                </td>
                            </tr>
                        }
                    </table>
                }
            }

        </div>
        <div>
            @{
                var receiversBcc = Model.EmailFolderMessage
                                             .EmailFolderMessageReceivers
                                             .Where(x => x.EmailMessageReceiverType == EmailMessageReceiverType.BCC)
                                             .ToList();
                if (receiversTo.Any())
                {
                    <table>

                        @for (int i = 0; i < receiversBcc.Count; i++)
                        {
                            <tr>
                                <td class="pe-2">
                                    @if (i == 0)
                                    {
                                        <text>UDW:</text>
                                    }
                                </td>
                                <td>
                                    @receiversBcc[i].EmailAddress.AddressInfo
                                </td>
                            </tr>



                        }
                    </table>

                }

            }

        </div>
    </div>


</div>

<hr />

@if (Model.EmailFolderMessage.EmailFolderAttachments.Any())
{
    foreach (var attachment in Model.EmailFolderMessage.EmailFolderAttachments)
    {
        <button class="btn btn-light"
                onclick="downloadAttachment('@Url.Action("EmailFolderAttachment", "Folder", new { attachmentId = attachment.Id })', '@attachment.FileName')">
            @attachment.FileName
        </button>
    }
    <hr />
}



<div class="row">

    @if (Model.EmailFolderMessage.IsBodyHtml)
    {
        <iframe style="overflow-x: auto;" srcdoc="@Model.EmailFolderMessage.Body" class="col-12" />
    }
    else
    {
        <div class="col-12">
            @Model.EmailFolderMessage.Body
        </div>
    }
</div>


@helper FolderIcon(FolderAttributes attributes)
{
    if (attributes.HasFlag(FolderAttributes.Inbox))
    {
        <i class="bi bi-inbox"></i>
    }

    else if (attributes.HasFlag(FolderAttributes.Flagged))
    {
        <i class="bi bi-star"></i>
    }

    else if (attributes.HasFlag(FolderAttributes.Sent))
    {
        <i class="bi bi-send"></i>
    }

    else if (attributes.HasFlag(FolderAttributes.Drafts))
    {
        <i class="bi bi-file-earmark"></i>
    }

    else if (attributes.HasFlag(FolderAttributes.Junk))
    {
        <i class="bi bi-exclamation-octagon"></i>
    }
    else if (attributes.HasFlag(FolderAttributes.Trash))
    {
        <i class="bi bi-trash"></i>
    }
    else if (attributes.HasFlag(FolderAttributes.All))
    {
        <i class="bi bi-envelope"></i>
    }
    else
    {
        <i class="bi bi-folder"></i>
    }
}

EmailSenderAspNetMvc/Views/Folder/FolderMessages.cshtml
@using EmailSenderAspNetMvc.Models.ViewModels
@using MailKit


@model DisplayEmailFolderMessagesViewModel

<h3>@FolderIcon(@Model.EmailFolder.Attributes) @Model.EmailFolder.Name</h3>

<hr />

@if ((Model.EmailMessageFolderMessages != null) && (Model.EmailMessageFolderMessages.Count > 0))
{
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                @if (Model.EmailFolder.Attributes.HasFlag(MailKit.FolderAttributes.Drafts)
                  || Model.EmailFolder.Attributes.HasFlag(MailKit.FolderAttributes.Sent))
                {
                    <th scope="col">Do</th>
                }
                else
                {
                    <th scope="col">Od</th>
                }

                <th scope="col">Tytuł</th>
                <th scope="col" style="min-width: 150px;">Data i godzina</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var message in Model.EmailMessageFolderMessages)
            {
                <tr onclick="showMessage(@Model.EmailFolder.Id, @message.Id)">
                    <td>
                        @if (Model.EmailFolder.Attributes.HasFlag(MailKit.FolderAttributes.Drafts)
                        || Model.EmailFolder.Attributes.HasFlag(MailKit.FolderAttributes.Sent))
                        {


                            if (message.EmailFolderMessageReceivers != null && message.EmailFolderMessageReceivers.Count > 0)
                            {

                                var diplayedReceiversAmount = 2;

                                for (int i = 0; i < message.EmailFolderMessageReceivers.Count; i++)
                                {

                                    if (!string.IsNullOrWhiteSpace(@message.EmailFolderMessageReceivers.ElementAt(i).EmailAddress.DisplayName))
                                    {
                                        <text>
                                            @message.EmailFolderMessageReceivers.ElementAt(i).EmailAddress.AddressInfo
                                        </text>
                                    }
                                    else
                                    {
                                        <text>
                                            @message.EmailFolderMessageReceivers.ElementAt(i).EmailAddress.Address
                                        </text>
                                    }
                                    if (i < message.EmailFolderMessageReceivers.Count - 1)
                                    {
                                        <text>;</text>
                                    }

                                    if (i + 1 == diplayedReceiversAmount
                                        && diplayedReceiversAmount < @message.EmailFolderMessageReceivers.Count)
                                    {
                                        <text>+@(message.EmailFolderMessageReceivers.Count - diplayedReceiversAmount)</text>
                                        break;
                                    }
                                    <br />
                                }
                            }
                        }
                        else
                        {
                            if (!string.IsNullOrWhiteSpace(message.From.DisplayName))
                            {
                                @message.From.DisplayName
                            }
                            else
                            {
                                @message.From.Address
                            }

                        }


                    </td>
                    <td>
                        @message.Subject
                    </td>
                    <td>
                        @((message.Date.ToLocalTime()).ToString("dd-MM-yyyy HH:mm"))
                    </td>
                </tr>
            }

        </tbody>

    </table>
}
else
{
    <h5>Ten folder jest pusty</h5>
}


@helper FolderIcon(FolderAttributes attributes)
{
    if (attributes.HasFlag(FolderAttributes.Inbox))
    {
        <i class="bi bi-inbox"></i>
    }

    else if (attributes.HasFlag(FolderAttributes.Flagged))
    {
        <i class="bi bi-star"></i>
    }

    else if (attributes.HasFlag(FolderAttributes.Sent))
    {
        <i class="bi bi-send"></i>
    }

    else if (attributes.HasFlag(FolderAttributes.Drafts))
    {
        <i class="bi bi-file-earmark"></i>
    }

    else if (attributes.HasFlag(FolderAttributes.Junk))
    {
        <i class="bi bi-exclamation-octagon"></i>
    }
    else if (attributes.HasFlag(FolderAttributes.Trash))
    {
        <i class="bi bi-trash"></i>
    }
    else if (attributes.HasFlag(FolderAttributes.All))
    {
        <i class="bi bi-envelope"></i>
    }
    else
    {
        <i class="bi bi-folder"></i>
    }
}

EmailSenderAspNetMvc/Views/Folder/Folders.cshtml
@using MailKit
@using EmailSenderAspNetMvc.Models.Domains

@model IEnumerable<EmailFolder>

@{
    ViewBag.Title = "Skrzynka pocztowa";
}




<div class="row">
    <div class="just-padding col-lg-3">
        <h2>Skrzynka pocztowa</h2>
        <div class="list-group list-group-root well">
            @ShowTree(Model)
        </div>
    </div>
    <div id="messages"
         class="just-padding col-9">

    </div>
</div>


@helper ShowTree(IEnumerable<EmailFolder> folders)
{
    foreach (var folder in folders)
    {

        if ((folder.Attributes & FolderAttributes.NonExistent) == 0)
        {
            if ((folder.EmailFolders == null
              || folder.EmailFolders.Count == 0
              || (folder.Attributes & FolderAttributes.HasNoChildren) != 0))
            {
                <a href="#"
                   class="list-group-item"
                   onclick="showMessages(@folder.Id, $(this))">
                    <span class="ms-3">
                        @FolderIcon(folder.Attributes)
                        @folder.Name
                    </span>
                </a>
            }
            else
            {
                <a href="#folder-@folder.Id"
                   class="list-group-item collapsed"
                   data-bs-toggle="collapse"
                   onclick="showMessages(@folder.Id, $(this))">
                    <i class="bi bi-chevron-right"></i>
                    <span>
                        @FolderIcon(folder.Attributes)
                        @folder.Name
                    </span>
                </a>
                <div class="list-group collapse" id="folder-@folder.Id">
                    @ShowTree(folder.EmailFolders)
                </div>
            }
        }



    }
}


@helper FolderIcon(FolderAttributes attributes)
{
    if (attributes.HasFlag(FolderAttributes.Inbox))
    {
        <i class="bi bi-inbox"></i>
    }

    else if (attributes.HasFlag(FolderAttributes.Flagged))
    {
        <i class="bi bi-star"></i>
    }

    else if (attributes.HasFlag(FolderAttributes.Sent))
    {
        <i class="bi bi-send"></i>
    }

    else if (attributes.HasFlag(FolderAttributes.Drafts))
    {
        <i class="bi bi-file-earmark"></i>
    }

    else if (attributes.HasFlag(FolderAttributes.Junk))
    {
        <i class="bi bi-exclamation-octagon"></i>
    }
    else if (attributes.HasFlag(FolderAttributes.Trash))
    {
        <i class="bi bi-trash"></i>
    }
    else if (attributes.HasFlag(FolderAttributes.All))
    {
        <i class="bi bi-envelope"></i>
    }
    else
    {
        <i class="bi bi-folder"></i>
    }
}



@section Scripts
{
    <script type="text/javascript">

        $(function () {
            (function ($) {
                var MutationObserver = window.MutationObserver || window.WebKitMutationObserver || window.MozMutationObserver;

                $.fn.attrchange = function (callback) {
                    if (MutationObserver) {
                        var options = {
                            subtree: false,
                            attributes: true
                        };

                        var observer = new MutationObserver(function (mutations) {
                            mutations.forEach(function (e) {
                                callback.call(e.target, e.attributeName);
                            });
                        });

                        return this.each(function () {
                            observer.observe(this, options);
                        });

                    }
                }
            })(jQuery);


            $(document).ready(function () {

                setLastItemClass();


                $('.list-group').attrchange(function (attrName) {

                    if (attrName == 'class') {
                        setLastItemClass();
                        setCollapseIcon();
                    }


                });
            });

            $('.list-group-item').on('click', function () {
                $('.bi', this)
                    .toggleClass('bi-chevron-right')
                    .toggleClass('bi-chevron-down');
            });


        });

        function setLastItemClass() {

            let items = $('.list-group-item');

            items.removeClass('list-group-item-last');


            for (let i = items.length - 1; i >= 0; i--) {
                let item = $(items[i]);


                if ((item.parents('.list-group.collapse.show')[0] != null
                    && item.parents('.list-group.collapse:not(.show)')[0] == null)
                    || item.parent('.list-group-root')[0] != null) {
                    item.addClass('list-group-item-last');
                    break;
                }
            }
        }

        function setCollapseIcon() {

            $(".list-group-item > i").each(function () {
                if ($(this).parent(".collapsed")[0] != null) {
                    $(this).removeClass('bi-chevron-down');
                    $(this).addClass('bi-chevron-right');
                } else {
                    $(this).removeClass('bi-chevron-right');
                    $(this).addClass('bi-chevron-down');
                }
            });
        }

        function showMessages(folderId, link) {

            $('.list-group-item').removeClass('active');

            link.addClass('active');

            $.ajax({
                    type: 'POST',
                    url: "@Url.Action("EmailFolderMessages", "Folder")",
                    data: {
                        folderId: folderId
                    },
                    success: function (messagesView) {
                                $('#messages').html(messagesView)
                             },
                    error: function (data) {
                        alert(data.Message);
                    },
                    dataType: 'html'
                }
            );
        }

        function showFolderContent(folderId) {
            $.ajax({
                    type: 'POST',
                    url: "@Url.Action("EmailFolderMessages", "Folder")",
                    data: {
                        folderId: folderId
                    },
                    success: function (messagesView) {
                                $('#messages').html(messagesView)
                             },
                    error: function (data) {
                        alert(data.Message);
                    },
                    dataType: 'html'
                }
            );
        }

        function showMessage(folderId, messageId) {
            $.ajax({
                    type: 'POST',
                    url: "@Url.Action("EmailFolderMessage", "Folder")",
                    data: {
                        folderId: folderId,
                        messageId: messageId
                    },
                    success: function (messageView) {
                        $('#messages').html(messageView)
                        $('iframe').contents().find('body').css({ "min-height": "100", "overflow": "hidden" });
                        setInterval("$('iframe').height($('iframe').contents().find('body').height() + 20)", 1);
                    },
                    error: function (data) {
                        alert(data.Message);
                    },
                    dataType: 'html'
                }
            );
        }

        function downloadAttachment(url, fileName) {
            // Create a link element
            var link = document.createElement("a");

            // Set the link's href attribute to the file URL
            link.href = url;

            // Set the link's download attribute
            link.download = fileName;

            // Add the link to the DOM
            document.body.appendChild(link);

            // Trigger the download
            link.click();

            // Remove the link from the DOM
            document.body.removeChild(link);
        }

    </script>
}